respown_point: [[1.5, 0.0, 90.0],
                [1.5, 1.5, 120.0], 
                [0.0, 2.5 ,180.0],
                [-1.5, 1.5, -150.0],
                [-1.5, 0.0, -90.0],
                [-1.5, -1.5, -60.0],
                [0.0, -2.5, 0.0],
                [1.5, -2.5, 45.0],
                ]